name: Build
on: 
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string
      os:
        required: true
        type: string
      shell:
        required: true
        type: string
jobs:
  build:
    runs-on: ${{ inputs.os }}
    defaults:
      run:
        shell: ${{ inputs.shell }}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          python-version: ${{ inputs.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest
          mamba-version: "*"
          use-mamba: true
      - name: build
        run: pyinstaller launcher.spec ${{ inputs.os }}
    
      - name: Upload Installer
        uses: actions/upload-artifact@v2
        with:
          name: installer-${{ inputs.python-version }}-${{ inputs.os }}
          path: |
            dist/*